### ISSUE TITLE
Turning off an active preset turns off all current plugins and can clear important data from other plugins

### ISSUE THREAD

**Issue by ColemanDunn** [antero111/plugin-presets#2] opened 2021-06-06 18:33 UTC
This may be a grey area, but in my opinion, was definitely not expected behavior. Recently I was in the wildy where I like to turn on player indicators and upon turning them on I realized I should make a preset, so I did. Upon leaving the wilderness I turned off the player indicators plugin but then realized my wilderness preset was still see to on. Naturally, I thought it would have turned off since the wildy preset was no longer fulfilled and would turn on again if I were to update the preset. However, it was still on, so in order to re-turn it on when again entering the wilderness I turned it off, and BAM right then and there my whole runelite froze for a good moment, and all of the sudden my whole runelite sidebar icons were gone except for the notes tab and I realized all of my plugins were turned off. So I immediately turned the preset back on to get my plugins back to and to my realization there were still plugins missing from the sidebar so I went back into my plugins and turned them back on. Everything was fine in the end except my supplies tracker was all cleared which is unfortunate. 

Again I am not sure this should be completely classified as a bug, but I feel it was certainly not intended behavior, and should possibly come with a warning that all of your plugins will get turned off. 

There are obviously more, but possible solutions to this are: 

- to just leave all current plugins turned on in the event that the current plugins turned off (meaning all created presets are now set to off)

- upon creation of the first preset create an invisible "default" preset that the plugins can fall back on in the event that all presets are turned off

- along with these possibly automatically turn off a preset if the user changes the settings since the current settings now no longer match a preset to be turned back in of the user updates the preset to the current settings akin to creating a preset in the first place. This may not be possible in the first place, but if so this could even be extended to turning off and on certain presets in the event that the user manually toggles their plugins to match a presets

Thanks for the read and thanks for this great plugin. This is also definitely the greatest solution to runelite's lack of support for multiple accounts. This is definitely addressing something that has much been needed in runelite for a long time.

**Comment by antero111** [comment] 2021-06-07 17:47
Currently this behaviour you experienced is working as intended but you raised some points that need polishing. 

Currently if one has a preset active and then turns some plugins on/off the preset does not "turn off" or tell you that some settings were modified. This caused your confusion when turning off the player indicators plugin. After that you tried to fix the confusion by turning off the preset and that caused your client to freeze and plugins were turned off. Currently turning off a preset means that all the plugins in the preset will be turned off. This causes the client to freeze for a moment because runelite has to turn 10's of plugins off. Tbh this is really bad and will get changed.

To fix this: when one modifies plugin settings (eg. disables the player indicators plugin) the active presets needs to be set off or atleast say some settings were changed and preset unloading (turning off) will need to get revamped or worded better.

**Comment by antero111** [comment] 2021-06-13 18:37
This should be fixed in the upcoming v1.4. 

The plugin now informs users that they have "unsaved" plugin configurations and displays a confirmation message if one tries to load other presets with unsaved plugin configurations. Removed the preset unloading to reduce confusion. Also now if you manually turn some plugins on/off to match certain preset the plugin now "switches" to that preset. 

Will close this issue once the update gets merged.

**Closed** 2021-06-15 10:03 UTC
Labels: enhancement
