### ISSUE TITLE
Small issues with Custom Keys

### ISSUE THREAD

**Issue by Jademalo** [antero111/plugin-presets#29] opened 2022-08-31 12:21 UTC
Absolutely love this feature, but I've come across a few little bugs.
I was wanting to add the ability to have two separate sets of notes for my different characters, so wanted to add `notes.notesData` as a custom key.

First of all, custom keys cannot be added if a profile is set to "Cloud" rather than "Local".
Once the key has been added it's fine to set back to Cloud, but for whatever reason you can't add a custom key if you're on a cloud profile's settings page.
In addition, custom keys cannot be added if the plugin is set to "Not Included".
You need to have something in that specific plugin set to Included before it will let a custom key be added.

Secondly, if I just have the custom key selected for Notes and not `Plugin on/off`, when I load the preset it disables the notes plugin. I've checked the json for the preset, and I don't understand why the plugin is being disabled when the preset is loaded. 
```json
{"id":1661947430400,"name":"Notes","local":true,"pluginConfigs":[{"name":"Notes","configName":"notes","settings":[{"name":"Notes Data","key":"notesData","value":"Test Notes for Issue","customConfigName":"notes","configName":"notes"}]}]}
```
This one isn't too hard to work around since I can just save the plugin on/off state, but it definitely seems like unintended behaviour.

Finally, If a custom key is deleted, it's associated data will only be deleted from the profile you're on when you delete it. Other profiles will have the option of the key deleted in the list, but the associated data will still be there and loading those profiles will still load the data associated with the key.
For example, if I have two profiles with custom notes data and go into the first profile and delete the custom key, when I load the second profile it will load the notes data even though the key isn't visible in the list.

**Comment by antero111** [comment] 2022-08-31 16:10
Hi, some of those I have also noted when the update pr was made. I'll try to fix those to the next version.

**Comment by Jademalo** [comment] 2022-09-03 18:00
Another issue to add to these - It seems that custom keys disappear on a client restart if the profiles that use the custom keys are set to Cloud.
At least, that's what I think is causing it, but my custom Notes key entry keeps disappearing. The data is still there and it loads the data in the profile, but since the key has vanished it doesn't show as "modified" and can't be updated without re-adding the key.

**Comment by antero111** [comment] 2022-09-04 15:32
I'll check that also when fixing these. There is something wrong with handling custom settings when they are saved to cloud.

**Comment by antero111** [comment] 2022-10-05 17:08
Hi, https://github.com/antero111/plugin-presets/commit/eef0e7de321e9bd76acb90e2813a632a71155c1e has some fixes to custom settings.

> First of all, custom keys cannot be added if a profile is set to "Cloud" rather than "Local".

Custom settings should work with presets stored to the RL config ("Cloud").

> In addition, custom keys cannot be added if the plugin is set to "Not Included"

This can now be done.

> Finally, If a custom key is deleted, it's associated data will only be deleted from the profile you're on when you delete it

This should be fixed since custom settings are now "per preset".

> Another issue to add to these - It seems that custom keys disappear on a client restart if the profiles that use the custom keys are set to Cloud.

Should not be the case anymore.


> Secondly, if I just have the custom key selected for Notes and not Plugin on/off, when I load the preset it disables the notes plugin. I've checked the json for the preset, and I don't understand why the plugin is being disabled when the preset is loaded.

There is still something wrong with custom settings and what you have described here is caused by that. I opened new issue for this. See https://github.com/antero111/plugin-presets/issues/34

I'll close this one since mostly these are now fixed to the next version.

**Closed by antero111** 2022-10-05 17:08 UTC
Labels: bug
