### ISSUE TITLE
Presets being deleted randomly

### ISSUE THREAD

**Issue by Costinett** [antero111/plugin-presets#55] opened 2023-02-15 05:28 UTC
So this is the 3rd time this has occured. A handful of presets randomly gets deleted while a few others stay and im unsure why this occurs or how to get them back

**Comment by antero111** [comment] 2023-02-15 10:07
I think that this is the same issue that is https://github.com/antero111/plugin-presets/issues/51. Unfortunately you can't restore the disappeared presets other than try to click the refresh presets button. 

Can you read that other issue and confirm if you can reproduce this?

I'm not sure why this is happening and haven't found a way to reproduce this reliably. Something causes the preset saving to fail and this can be caused by multiple of reasons.

**Comment by Costinett** [comment] 2023-02-17 05:01
I cannot reproduce. I'm thinking the only answer is to make sure i copy the presets to a backup folder for now. This plugin is great and this won't stop me from using it. Thanks.

**Comment by OskarOskar** [comment] 2023-02-18 19:50
pretty sure this happens for me when I have the "auto update" option enabled

**Comment by antero111** [comment] 2023-02-20 08:35
Can you describe more about how do they disappear when auto update is enabled? I still haven't been ablo to reproduce this reliably

**Comment by crab-pancake** [comment] 2023-03-02 13:41
Getting this issue very often, usually within a minute of pasting the presets back into the folder. 
```
2023-03-03 00:12:27 [AWT-EventQueue-0] WARN  c.pluginpresets.PluginPresetsStorage - Failed to load preset from .runelite\presets\.default.json, .runelite\presets\default.json (The process cannot access the file because it is being used by another process)
2023-03-03 00:13:41 [Client] WARN  c.pluginpresets.PluginPresetsStorage - Could not delete default.json
2023-03-03 00:13:41 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1543)
	at com.pluginpresets.PluginPresetsStorage.savePresets(PluginPresetsStorage.java:114)
	at com.pluginpresets.PluginPresetsPlugin.savePresets(PluginPresetsPlugin.java:348)
	at com.pluginpresets.PluginPresetsPresetEditor.updateEditedPreset(PluginPresetsPresetEditor.java:454)
	at com.pluginpresets.PluginPresetsPresetEditor.updateAllModified(PluginPresetsPresetEditor.java:382)
	at com.pluginpresets.PluginPresetsPlugin.onConfigChanged(PluginPresetsPlugin.java:231)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
```

most recent message, tho there are a lot more if needed

**Comment by mastersuleman** [comment] 2023-03-12 06:02
Happening to me too. 
I remade the presets and added cloud sync but same thing seemed to occur. So now im just keeping it local and making a backup

**Comment by WholesomeDogg0** [comment] 2023-05-27 16:29
Still having this issue myself. It used to randomly show a few of the toggle switches missing and then reappear later but last night every single toggle option got deleted while I was playing and the preset plugin settings folder is completely empty :/

**Comment by antero111** [comment] 2023-05-27 19:15
Could you think of something that you did before the presets disappeared e.g. switched core profiles or changes some settings on some other plugin? Did you have the auto update enabled at some preset? 

I'm thinking of some backup functionality to the plugin so that after you have made your presets, you could make a preset backup file to store in a different folder. Tho thats just same thing as storing copies of your presets in other folder...

**Comment by WholesomeDogg0** [comment] 2023-05-27 20:01
I had toggled one preset then closed the sidebar as I've done countless times before. Some time later opened the sidebar and then saw everything was gone. Didn't do anything with presets on my sidebar between the time I opened & closed it. I think I had auto-update on one of the presets, but no way to check now... :/

**Comment by antero111** [comment] 2023-05-27 21:53
Ok, thanks for the reply. I'll try to debug this more when I have some time...

**Comment by antero111** [comment] 2023-06-09 11:20
Noticed that switching core profiles in some cases deletes all presets from the preset folder.

**Comment by Jademalo** [comment] 2023-06-28 10:18
Just had all of my profiles delete themselves, no idea why. Hopefully I can grab the backup from my other machine before they disappear on there too.

Hadn't launched the game in a while, did just there and the preset menu was empty. Was fine last time I loaded the game, and I didn't do anything to them between then and now.
Both local presets and cloud presets disappeared, interestingly.

**Comment by antero111** [comment] 2023-10-15 18:04
Fixed some issues with profile loading and auto updater in recent commits. `java.util.ConcurrentModificationException: null` with auto updater was fixed and I'd say it was the main problem all along...
Fixes will be available in the next plugin update.

Please open a new issue for the upcoming version if this still persists.

**Closed by antero111** 2023-10-15 18:04 UTC
Labels: bug, help wanted

**Comment by ArtsicleOfficial** [comment] 2024-01-05 19:37
This bug - randomly deleting presets - keeps happening to me and renders plugin presets barely usable. Unfortunate.
