### ISSUE TITLE
Could the plugin work with "runelite" options?

### ISSUE THREAD

**Issue by wzrddd** [antero111/plugin-presets#3] opened 2021-07-26 00:56 UTC
I'd like to change between "request focus - off" and "request focus - force" for my amethyst alt preset but it doesn't seem to save the setting

**Comment by wzrddd** [comment] 2021-07-26 01:18
doesn't matter anymore, cool plugin but from reading that other guys issue I'm paranoid about any of my settings resetting/losing data from supply tracker/loot logger ect

**Comment by antero111** [comment] 2021-07-29 12:33
Currently the "runelite" plugin (client settings) is considered as "ignored". It was by design because turning the "runelite" plugin off caused problems. Might try fix it so that the "runelite plugin" options are also included in the plugin.

**Comment by jfabellera** [comment] 2021-09-16 23:48
Any progress on this?

**Comment by jfabellera** [comment] 2021-09-16 23:56
> It was by design because turning the "runelite" plugin off caused problems

Also what do you mean by turning the "runelite" plugin off? I don't see a toggle to turn it off.

**Comment by antero111** [comment] 2021-09-17 10:20
Hey, in runelite the whole "runelite" is considered as a plugin like all the other plugins. That plugin has settings to internal runelite settings like window size etc. You can't turn it off from the runelite ui because its set as "hidden" but you can disable it programmatically. Currently the plugin loops all of the available plugins and changes its settings and turns them on/off. 

Turning the runelite plugin off is something the runelite devs didn't think that someone would do. It literally disables all the "runelite" functionality like plugins, it pretty much sets the client to the same state than the vanilla osrs client. In the beginning the plugin had a "unload preset" functionality that turned all the plugins that were on in that preset off. Turning some preset off also turned the runelite plugin off and kinda broke the client... This has been fixed now.

Originally the quick fix was to just simply ignore the runelite plugin. Well now if we wanted to save and use settings from the runelite plugin, we need to remove it from the ignored plugins and save its settings also to a preset. Turns out the runelite plugin somehow behaves differently than the rest of the plugins and their settings. 

I'll have look into if this could be implemented.

**Comment by septicsalmon** [comment] 2021-09-21 13:45
Just throwing in my hat for support for this.

**Comment by antero111** [comment] 2021-09-26 17:55
The latest version of the plugin now saves runelite settings to presets.

**Closed by antero111** 2021-09-26 17:55 UTC
Labels: enhancement
