### ISSUE TITLE
Causes runelite to hang when switching the new runelite profiles

### ISSUE THREAD

**Issue by AustinGarrettR** [antero111/plugin-presets#58] opened 2023-03-13 02:26 UTC
Recently runelite added a profile switcher. It does not do everything plugin presets does, and I value the plugin still.
However, when switching runelite profiles it will cause the client to hang for 1-3 minutes when the plugin is enabled.

**Comment by antero111** [comment] 2023-03-13 17:32
Are you able describe some exact steps to reproduce this? I haven't had any issues with core profiles with plugin presets resently. Does the issue still arise if you uninstall the plugin?

**Comment by AustinGarrettR** [comment] 2023-03-14 00:08
The issue will go away when the plugin is disabled or uninstalled. As soon as it's enabled, swapping to another profile hangs the client.

If I make a brand new core profile, and change to the normal profile with the plugin, it will be fine. But changing from the profile with the plugin enabled, to a blank profile it will lock up.

Seems to be an issue with stopping the plugin on switch.

**Comment by antero111** [comment] 2023-03-14 05:37
Anything on the logfile?

_But changing from the profile with the plugin enabled, to a blank profile it will lock up.

Seems to be an issue with stopping the plugin on switch._

Can you elaborate this more? What kind of presets and profiles you have? Are you logged into ReneLite account?

**Comment by Jademalo** [comment] 2023-07-16 16:25
![image](https://github.com/antero111/plugin-presets/assets/386846/fadfce7d-cf77-4939-a25f-9e78fa7d4bb4)

Had a hang on changing a profile that I couldn't figure out, Adam recommended profiling it. Figured out this was the culprit, and hopefully this is useful!

**Comment by antero111** [comment] 2023-07-17 11:30
Hi Jademalo, I think that this might be caused by the plugin checking all of the config changes when switching profiles. I'll need to fix this once I have some time.

**Comment by antero111** [comment] 2023-10-15 17:59
This is most likely fixed now in https://github.com/antero111/plugin-presets/commit/6e9370a9b1c6d4c6600d0f2cd59ae0cf1d57adb4. Profiles and the plugins config changed handler collapsed quite badly and caused the lag.

**Closed by antero111** 2023-10-15 17:59 UTC
Labels: bug
